version: '3.8'

services:

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "5432:5432"

  admin:
    image: dpage/pgadmin4:4.18
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    links:
      - "db:db_server"